"""
Generate a BMP180 driver library from validated controller IR + sensor IR.

Emits two files:
1. bmp180_driver.h — public API declarations (status enum + function prototypes)
2. bmp180_driver.cpp — implementation (I2C via Wire, no Serial, no test logic)

EVERY sensor constant (addresses, commands, timings) is drawn from the sensor IR.
The controller IR provides I2C peripheral metadata for comments.
Zero hardcoded hex literals — if it's not in an IR, it's not in the output.
"""

from codegen.ir_parser import PeripheralIR
from codegen.sensor_ir_parser import SensorIR


def generate_driver(ir: PeripheralIR, sensor_ir: SensorIR) -> dict:
    """Returns {"header": str, "source": str} for bmp180_driver.h and bmp180_driver.cpp."""

    ctr_reg = ir.reg_by_name("I2C_CTR_REG")
    ms_mode = ctr_reg.field_by_name("I2C_MS_MODE") if ctr_reg else None
    sda_force = ctr_reg.field_by_name("I2C_SDA_FORCE_OUT") if ctr_reg else None
    scl_force = ctr_reg.field_by_name("I2C_SCL_FORCE_OUT") if ctr_reg else None

    ir_notes = []
    if ms_mode:
        ir_notes.append(f"I2C_MS_MODE (bit {ms_mode.bit_offset}): {ms_mode.description}")
    if sda_force:
        ir_notes.append(f"I2C_SDA_FORCE_OUT (bit {sda_force.bit_offset}): reset={sda_force.reset_value} ({sda_force.description})")
    if scl_force:
        ir_notes.append(f"I2C_SCL_FORCE_OUT (bit {scl_force.bit_offset}): reset={scl_force.reset_value} ({scl_force.description})")

    filter_reg = ir.reg_by_name("I2C_SCL_FILTER_CFG_REG")
    if filter_reg:
        en_field = filter_reg.field_by_name("I2C_SCL_FILTER_EN")
        if en_field:
            ir_notes.append(f"I2C_SCL_FILTER_EN (bit {en_field.bit_offset}): reset={en_field.reset_value} (filter enabled by default)")

    ir_comment = "\n".join(f" *   - {n}" for n in ir_notes)

    reset_cmd = sensor_ir.cmd_by_name("SOFT_RESET")
    temp_cmd = sensor_ir.cmd_by_name("READ_TEMPERATURE")
    reset_timing = sensor_ir.timing_by_name("soft_reset_time")
    temp_timing = sensor_ir.timing_by_name("temperature_conversion")

    reset_delay_ms = (reset_timing.microseconds // 1000) if reset_timing else 10
    temp_delay_ms = ((temp_timing.microseconds // 1000) + 1) if temp_timing else 5

    header_comment = f'''/*
 * EmbeddPilot V1.1 — Generated by deterministic template
 *
 * Controller IR: {ir.datasheet_source}
 * Peripheral: {ir.peripheral} (base: {ir.base_address})
 * Register count: {len(ir.registers)}, Field count: {sum(len(r.fields) for r in ir.registers)}
 *
 * Sensor IR: {sensor_ir.datasheet_source}
 * Sensor: {sensor_ir.name} ({sensor_ir.manufacturer}) @ {sensor_ir.i2c_address}
 *
 * IR-derived controller notes:
{ir_comment}
 *
 * All sensor constants are IR-driven (sensor-ir.json).
 * All controller metadata is IR-driven (controller-ir.json).
 */'''

    header = f'''{header_comment}

#ifndef BMP180_DRIVER_H
#define BMP180_DRIVER_H

#include <Arduino.h>
#include <Wire.h>

typedef enum {{
    BMP180_OK = 0,
    BMP180_ERR_I2C,
    BMP180_ERR_BAD_CHIP_ID
}} bmp180_status_t;

bmp180_status_t bmp180_init(TwoWire &wire, int sda_pin, int scl_pin, uint32_t freq);
uint8_t bmp180_chip_id(void);
bmp180_status_t bmp180_soft_reset(void);
bmp180_status_t bmp180_read_raw_temperature(int32_t *raw_temp);
bmp180_status_t bmp180_read_register(uint8_t reg, uint8_t *value);
bmp180_status_t bmp180_write_register(uint8_t reg, uint8_t value);

#endif
'''

    source = f'''{header_comment}

#include "bmp180_driver.h"

/* --- Sensor Constants (ALL from sensor-ir.json) --- */
static const uint8_t SENSOR_ADDR      = {sensor_ir.i2c_address};
static const uint8_t REG_CHIP_ID      = {sensor_ir.chip_id_register};
static const uint8_t EXPECTED_CHIP_ID = {sensor_ir.chip_id_expected};
static const uint8_t REG_RESET        = {reset_cmd.target_register};
static const uint8_t RESET_CMD        = {reset_cmd.value};
static const uint8_t REG_CTRL_MEAS    = {temp_cmd.target_register};
static const uint8_t MEAS_TEMP_CMD    = {temp_cmd.value};
static const uint8_t REG_DATA_START   = {sensor_ir.reg_by_name("OUT_MSB").address};
static const uint8_t DATA_BURST_LEN   = 3;

/* --- Module State --- */
static TwoWire *_wire = nullptr;
static uint8_t _chip_id = 0xFF;

/* --- Internal I2C Helpers --- */

static bmp180_status_t read_reg_internal(uint8_t reg, uint8_t *value) {{
    _wire->beginTransmission(SENSOR_ADDR);
    _wire->write(reg);
    if (_wire->endTransmission(false) != 0) {{
        return BMP180_ERR_I2C;
    }}
    _wire->requestFrom(SENSOR_ADDR, (uint8_t)1);
    if (_wire->available()) {{
        *value = _wire->read();
        return BMP180_OK;
    }}
    return BMP180_ERR_I2C;
}}

static bmp180_status_t write_reg_internal(uint8_t reg, uint8_t value) {{
    _wire->beginTransmission(SENSOR_ADDR);
    _wire->write(reg);
    _wire->write(value);
    if (_wire->endTransmission() != 0) {{
        return BMP180_ERR_I2C;
    }}
    return BMP180_OK;
}}

static bmp180_status_t read_burst_internal(uint8_t start_reg, uint8_t *buf, uint8_t len) {{
    _wire->beginTransmission(SENSOR_ADDR);
    _wire->write(start_reg);
    if (_wire->endTransmission(false) != 0) {{
        return BMP180_ERR_I2C;
    }}
    _wire->requestFrom(SENSOR_ADDR, len);
    for (uint8_t i = 0; i < len; i++) {{
        if (!_wire->available()) return BMP180_ERR_I2C;
        buf[i] = _wire->read();
    }}
    return BMP180_OK;
}}

/* --- Public API (see contracts/DRIVER_API.md) --- */

bmp180_status_t bmp180_init(TwoWire &wire, int sda_pin, int scl_pin, uint32_t freq) {{
    _wire = &wire;
    _wire->begin(sda_pin, scl_pin, freq);

    uint8_t id;
    bmp180_status_t status = read_reg_internal(REG_CHIP_ID, &id);
    if (status != BMP180_OK) {{
        return BMP180_ERR_I2C;
    }}
    _chip_id = id;
    if (id != EXPECTED_CHIP_ID) {{
        return BMP180_ERR_BAD_CHIP_ID;
    }}
    return BMP180_OK;
}}

uint8_t bmp180_chip_id(void) {{
    return _chip_id;
}}

bmp180_status_t bmp180_soft_reset(void) {{
    bmp180_status_t status = write_reg_internal(REG_RESET, RESET_CMD);
    if (status != BMP180_OK) {{
        return BMP180_ERR_I2C;
    }}
    delay({reset_delay_ms});

    uint8_t id;
    status = read_reg_internal(REG_CHIP_ID, &id);
    if (status != BMP180_OK) {{
        return BMP180_ERR_I2C;
    }}
    _chip_id = id;
    if (id != EXPECTED_CHIP_ID) {{
        return BMP180_ERR_BAD_CHIP_ID;
    }}
    return BMP180_OK;
}}

bmp180_status_t bmp180_read_raw_temperature(int32_t *raw_temp) {{
    bmp180_status_t status = write_reg_internal(REG_CTRL_MEAS, MEAS_TEMP_CMD);
    if (status != BMP180_OK) {{
        return BMP180_ERR_I2C;
    }}
    delay({temp_delay_ms});

    uint8_t data[DATA_BURST_LEN];
    status = read_burst_internal(REG_DATA_START, data, DATA_BURST_LEN);
    if (status != BMP180_OK) {{
        return BMP180_ERR_I2C;
    }}
    *raw_temp = ((int32_t)data[0] << 8) | (int32_t)data[1];
    return BMP180_OK;
}}

bmp180_status_t bmp180_read_register(uint8_t reg, uint8_t *value) {{
    return read_reg_internal(reg, value);
}}

bmp180_status_t bmp180_write_register(uint8_t reg, uint8_t value) {{
    return write_reg_internal(reg, value);
}}
'''

    return {"header": header, "source": source}
