"""
Generate a C header file with register definitions from parsed IR.

This is the primary IR-to-code artifact. Every #define comes from the IR;
nothing is pulled from training memory. The header is consumed by the
driver and any other code that needs to reference peripheral registers.
"""

from codegen.ir_parser import PeripheralIR, Register, BitField


def _guard_name(peripheral: str) -> str:
    return f"{peripheral.upper()}_REGS_H"


def _reg_define_name(reg: Register) -> str:
    return reg.name.upper()


def _field_mask_name(reg: Register, field: BitField) -> str:
    return f"{field.name}_M"


def _field_shift_name(reg: Register, field: BitField) -> str:
    return f"{field.name}_S"


def _field_value_name(reg: Register, field: BitField) -> str:
    return f"{field.name}_V"


def generate_header(ir: PeripheralIR) -> str:
    lines = []
    guard = _guard_name(ir.peripheral)

    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append(f"/* {ir.peripheral} Register Definitions */")
    lines.append(f"/* Source: {ir.datasheet_source} */")
    lines.append(f"/* MCU: {ir.mcu_family} ({ir.mcu_part}) */")
    lines.append(f"/* Auto-generated by EmbeddPilot from controller-ir.json */")
    lines.append("")
    lines.append(f"#define {ir.peripheral}_BASE_ADDR  {ir.base_address}")
    lines.append("")

    current_group = None
    for reg in ir.registers:
        group = _detect_group(reg.name)
        if group != current_group:
            current_group = group
            lines.append(f"/* --- {group} --- */")
            lines.append("")

        lines.append(f"/* {reg.description} */")
        lines.append(f"#define {_reg_define_name(reg)}  ({ir.peripheral}_BASE_ADDR + {reg.offset})")
        lines.append(f"#define {_reg_define_name(reg)}_RST  {reg.reset_value}")
        lines.append("")

        for field in sorted(reg.fields, key=lambda f: f.bit_offset, reverse=True):
            if field.access == "RESERVED":
                continue

            mask_val = field.mask
            lines.append(f"#define {_field_shift_name(reg, field)}  {field.bit_offset}")
            lines.append(f"#define {_field_mask_name(reg, field)}  0x{mask_val:08X}")
            lines.append(f"#define {_field_value_name(reg, field)}  0x{field.max_value:X}")

            if field.enum_values:
                for val, label in sorted(field.enum_values.items(), key=lambda x: int(x[0])):
                    safe_label = label.upper().replace(" ", "_").replace("-", "_")
                    lines.append(f"#define {field.name}_{safe_label}  {val}")

            lines.append("")

    lines.append(f"/* Accessor macros */")
    lines.append(f"#define REG_READ(addr)        (*(volatile uint32_t *)(addr))")
    lines.append(f"#define REG_WRITE(addr, val)  (*(volatile uint32_t *)(addr) = (val))")
    lines.append(f"#define REG_SET_BITS(addr, mask)    REG_WRITE((addr), REG_READ(addr) | (mask))")
    lines.append(f"#define REG_CLR_BITS(addr, mask)    REG_WRITE((addr), REG_READ(addr) & ~(mask))")
    lines.append(f"#define REG_SET_FIELD(addr, field, val)  \\")
    lines.append(f"    REG_WRITE((addr), (REG_READ(addr) & ~field##_M) | (((val) & field##_V) << field##_S))")
    lines.append(f"#define REG_GET_FIELD(addr, field)  \\")
    lines.append(f"    ((REG_READ(addr) & field##_M) >> field##_S)")
    lines.append("")
    lines.append(f"#endif /* {guard} */")
    lines.append("")

    return "\n".join(lines)


def _detect_group(reg_name: str) -> str:
    name = reg_name.upper()
    if "INT_RAW" in name or "INT_CLR" in name or "INT_ENA" in name or "INT_STATUS" in name:
        return "Interrupt Registers"
    if "COMD" in name:
        return "Command Registers"
    if "FILTER" in name:
        return "Filter Registers"
    if "SCL_LOW" in name or "SCL_HIGH" in name or "HOLD" in name or "SETUP" in name or "SAMPLE" in name:
        return "Timing Registers"
    if "FIFO" in name:
        return "FIFO Registers"
    if "CTR" in name or "SR" in name or "TO_" in name or "SLAVE_ADDR" in name:
        return "Configuration & Status Registers"
    return "Registers"
